version: '2'

services:
  db:
    image: mdillon/postgis:9.4

  redis:
    image: redis:3.0
  
  server:
    image: cloud-app:canary
    ports:
    - "3000:3000"
    command: py-skygear
    environment:
      API_KEY: changeme
      MASTER_KEY: changemenow
      APP_NAME: cloudapptest
      DATABASE_URL: postgres://postgres@db/postgres?sslmode=disable
      PLUGINS: PYTHON
      PYTHON_TRANSPORT: zmq
      PYTHON_PATH: python
      PYTHON_ARGS: "tcp://*:5555"

  build:
    image: cloud-app:canary
    command: sh -c "/build && cat /usr/src/assets/static/hello/index.txt"
    entrypoint: ""
    volumes:
    - ./test-app:/usr/src/app
